### ISSUE TITLE
react + typescript

### ISSUE THREAD

**Issue by stephenkopylov** [knocknote/pixi-after-effects#13]
Hello!

Is it possible to use this library with react and typescript? 

I'm trying to import it this way:
```typescript
import React from 'react';
import * as PIXI from 'pixi.js'
import * as PIXIAE from 'pixi-after-effects/dist/pixi-ae.js'

class App extends React.Component {
    componentDidMount(): void {
        var renderer = new PIXI.WebGLRenderer(2000, 600, {antialias: true, backgroundColor: 0x000000});
        document.body.appendChild(renderer.view);
        var stage = new PIXI.Container();
        var ae: any = null;
        var interceptor = new PIXIAE.AEDataInterceptor({
        ...
	}	

	render(){
		...
	}
}
```

but get this error:

<img width="700" alt="Screenshot 2019-06-28 at 1 56 22 AM" src="https://user-images.githubusercontent.com/5202281/60306346-7ae47b80-9948-11e9-910d-d583cd0fba79.png">

**Comment by sermmor** [comment]
Hello @stephenkopylov . I have the same error, it because two problems (I'll write you some solutions too):

1. Problems of compatibility between Pixi v5 and Pixi v4 (pixi-after-effects use Pixi v4 and not Pixi v5). This issue are solving in Pull Resquest #10 ( https://github.com/knocknote/pixi-after-effects/pull/10 ).

2. There aren't typescript headers support for this library. I done typescript headers in my fork ( https://github.com/sermmor/pixi-after-effects ), but I need to fix some webpack problems. I was thinking to resolve that problems but I prefer to wait to when the Pull Resquest #10 about Pixi v5 support will be resolved, and then I will add the typescript headers. Meanwhile, if you use Pixi v4, you could to pick the headers up from my fork and deal with it.

Regards!
